version: "3"

services:
    siteminder_backend_dev:
        container_name: siteminder_backend_dev
        restart: always
        env_file: 
            - ./.env
        ports:
            - "3000:3000"
        build:
            context: .
            dockerfile: Dockerfile
        command: ["yarn", "run", "start:dev"]

    
