version: 2.1
jobs:
    backend_build_job:
        docker:
            - image: circleci/node:12
        environment:
            SAMPLE: bonersquad
        
        steps:
            - checkout

            ##
            # @name
            # @description  Download and cache dependencies or fallback to using the latest cache if no exact match is found
            ##
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    
                    - v1-dependencies-

            ##
            # @name Install serverless
            ##
            - run: 
                name: install and configure serverless 
                command: | 
                    npm install -g serverless
                    serverless --version
                    serverless config credentials --provider aws --key $aws_access_key_id --secret $aws_secret_access_key


            ##
            # @name Install dependencies
            ##
            - run: yarn install 


            ##
            # @name
            # @description
            ##
            # - run:
            #     name: create .env file 
            #     command: |
            #         touch .env 
            #         # echo "SENDGRID_SECRET=$SENDGRID_SECRET" >> .env
            #         # echo "SENDGRID_TEMPLATE=$SENDGRID_TEMPLATE" >> .env
            #         # echo "aws_access_key_id=$aws_access_key_id" >> .env
            #         # echo "aws_secret_access_key=$aws_secret_access_key" >> .env
            #         ls 
            #         echo "remove this asap ..." && cat .env     

            ##
            # @name
            # @description
            ##


            ##
            # @name
            # @description
            ##


            ##
            # @name
            # @description
            ##


            ## 
            # @name Save cache 
            ##
            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}

workflows:
    master_workflow:
        jobs:
            - backend_build_job
