version: 2.1
jobs:
    backend_build_job:
        docker:
            - image: circleci/node:12
        environment:
            SAMPLE: bonersquad
        
        steps:
            - checkout

            ##
            # @name
            # @description  Download and cache dependencies or fallback to using the latest cache if no exact match is found
            ##
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    
                    - v1-dependencies-

            ##
            # @name Install 
            ##
            - run: yarn install 

            ##
            # @name Save cache 
            ##
            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}


            ##
            # @name
            # @description
            ##
            - run:
                name: build_step
                command: |
                    echo "hello world" 
                    echo "CIRCLE_WORKING_DIRECTORY is $CIRCLE_WORKING_DIRECTORY"
                    echo "SAMPLE is $SAMPLE"


workflows:
    master_workflow:
        jobs:
            - backend_build_job
