version: 2.1
jobs:
    backend_build_job:
        docker:
            - image: circleci/node:12
        environment:
            SAMPLE: bonersquad
        
        steps:
            - checkout

            ##
            # @name
            # @description  Download and cache dependencies or fallback to using the latest cache if no exact match is found
            ##
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    
                    - v1-dependencies-

            ##
            # @name Install 
            ##
            - run: yarn install 

            ##
            # @name Save cache 
            ##
            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}


            ##
            # @name
            # @description
            ##
            - run:
                name: create_env_file
                command: |
                    touch .env 
                    export SENDGRID_SECRET = $($SENDGRID_SECRET | base64 --decode)
                    echo "SENDGRID_SECRET=$SENDGRID_SECRET" >> .env
                    echo "SENDGRID_TEMPLATE=$SENDGRID_TEMPLATE" >> .env
                    echo "aws_access_key_id=$aws_access_key_id" >> .env
                    echo "aws_secret_access_key=$aws_secret_access_key" >> .env
                    ls 
                    echo "remove this asap ..." && cat .env 

            

workflows:
    master_workflow:
        jobs:
            - backend_build_job
